## -*- Mode: CPerl -*-
##
## File: DocClassify::Client.pm
## Author: Bryan Jurish <jurish@uni-potsdam.de>
## Description: abstract class for DocClassify server clients

package DocClassify::Client;
use DocClassify;
use Carp;
use strict;

##==============================================================================
## Globals
##==============================================================================

our @ISA = qw(DocClassify::Logger);

##==============================================================================
## Constructors etc.
##==============================================================================

## $obj = CLASS_OR_OBJ->new(%args)
##  + object structure: HASH ref
##    {
##     #...
##    }
sub new {
  my $that = shift;
  my $obj = bless({
		   ##
		   ##-- user args
		   @_
		  },
		  ref($that)||$that);
  $obj->initialize();
  return $obj;
}

## undef = $obj->initialize()
##  + called to initialize new objects after new()
sub initialize { return $_[0]; }

##==============================================================================
## Methods: Generic Client API: Connections
##==============================================================================

## $bool = $cli->connected
sub connected { return 0; }

## $bool = $cli->connect()
sub connect { return $_[0]->connected; }

## $bool = $cli->disconnect()
sub disconnect { return !$_[0]->connected; }

## @analyzers = $cli->analyzers()
sub analyzers { return qw(); }

##==============================================================================
## Methods: Generic Client API: Queries
##==============================================================================

## $tok = $cli->analyzeToken($analyzer, $tok, \%opts)
sub analyzeToken {
  my $cli = shift;
  $cli->logcroak("analyzeToken() method not implemented!");
}

## $sent = $cli->analyzeSentence($analyzer, $sent, \%opts)
sub analyzeSentence {
  my $cli = shift;
  $cli->logcroak("analyzeSentence() method not implemented!");
}

## $doc = $cli->analyzeDocument($analyzer, $doc, \%opts)
sub analyzeDocument {
  my $cli = shift;
  $cli->logcroak("analyzeDocument() method not implemented!");
}

## $doc = $cli->analyzeData($analyzer, $doc, \%opts)
sub analyzeData {
  my $cli = shift;
  $cli->logcroak("analyzeGeneric() method not implemented!");
}



1; ##-- be happy

__END__

##========================================================================
## POD DOCUMENTATION, auto-generated by podextract.perl, and edited

##========================================================================
## NAME
=pod

=head1 NAME

DocClassify::Client - abstract class for DocClassify server clients

=cut

##========================================================================
## SYNOPSIS
=pod

=head1 SYNOPSIS

 use DocClassify::Client;
 
 ##========================================================================
 ## Constructors etc.
 
 $cli = DocClassify::Client->new(%args);
 undef = $cli->initialize();
 
 ##========================================================================
 ## Methods: Generic Client API: Connections
 
 $bool = $cli->connected;
 $bool = $cli->connect();
 $bool = $cli->disconnect();
 
 ##========================================================================
 ## Methods: Generic Client API: Queries
 
 $doc = $cli->analyzeDocument($analyzer, $doc, \%opts);

=cut

##========================================================================
## DESCRIPTION
=pod

=head1 DESCRIPTION

Abstract base class / API specification.

=cut

##----------------------------------------------------------------
## DESCRIPTION: DocClassify::Client: Globals
=pod

=head2 Globals

=over 4

=item Variable: @ISA

DocClassify::Client inherits from
L<DocClassify::Logger|/DocClassify::Logger>.

=back

=cut

##----------------------------------------------------------------
## DESCRIPTION: DocClassify::Client: Constructors etc.
=pod

=head2 Constructors etc.

=over 4

=item new

 $obj = CLASS_OR_OBJ->new(%args);

%args, %$obj: none here; see subclass documentation for details.

=item initialize

 undef = $obj->initialize();

Called to initialize new objects after new().
Default implementation does nothing.

=back

=cut

##----------------------------------------------------------------
## DESCRIPTION: DocClassify::Client: Methods: Generic Client API: Connections
=pod

=head2 Methods: Generic Client API: Connections

=over 4

=item connected

 $bool = $cli->connected;

Returns true iff a connection to the selected server has been established.
Default implementation always returns false.

=item connect

 $bool = $cli->connect();

Establish a connection to the selected sever; returns true on success, false otherwise.
Default implementation just calls L</connected>().

=item disconnect

 $bool = $cli->disconnect();

Close current connection, if any.
Default implementation just calls L</connected>().

=back

=cut

##----------------------------------------------------------------
## DESCRIPTION: DocClassify::Client: Methods: Generic Client API: Queries
=pod

=head2 Methods: Generic Client API: Queries

=over 4

=item analyzeDocument

 $doc = $cli->analyzeDocument($analyzer, $doc, \%opts);

Server-side document analysis.
$analyzer is the name of an analyzer known to the server.

Default implementation just croak()s.

=back

=cut

##========================================================================
## END POD DOCUMENTATION, auto-generated by podextract.perl

##======================================================================
## Footer
##======================================================================

=pod

=head1 AUTHOR

Bryan Jurish E<lt>jurish@uni-potsdam.deE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2009-2010 by Bryan Jurish

This package is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.4 or,
at your option, any later version of Perl 5 you may have available.

=cut
